# This is a basic workflow to help you get started with Actions

name: Generate README every 15 min

# Controls when the action will run.
on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update:
     # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.6.0
          
      - run: yarn
      
      - run: node .
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}

      - name: Add to git repo
        run: |
          git add .
          git config --global user.name "Amy Sywe"
          git config --global user.email "asywe16@g.ucla.edu"
          git commit -m "Automated README update"
          
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
